# .nosana-ci.yml
nosana:
    description: Build Nosana Documentation

global:
    image: registry.hub.docker.com/library/node:18

    # Git, trigger on these branches
    trigger:
        branch:
            - master

    # Environment variables
    environment:
        APP_ENV: production  # comment here about this var

    # Allow pipeline to stop if one job fails
    allow_failure: true  # default: false

jobs: 

    # Install dependencies
    - name: install
      commands:
          - yarn ci 
          - yarn run lint 
      artifacts:  # artifact for the next job
          - name: node_modules
            path: ./

