[features]
seeds = false
skip-lint = false
[programs.devnet]
solana_hello_world = "FQgHznfVq79xGWAccg7oEk6Ai9MTqmmxAhebZAj2weFg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/kiran/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
